default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: localhost
  port: 3000
development:
  <<: *default
  database: my_api_development
test:
  <<: *default
  database: my_api_test
production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: my_api_production
  pool: 5
  username:
  password:
